### ISSUE TITLE
Dependency isolation

### ISSUE THREAD

**Issue by ThanhPhanz** [Nice3point/RevitToolkit#5]
I realized that when I inherit my command from ExternalCommand, it can no longer get value from static variables or settings. I think it's because the add-in was loaded from another assembly. Is there any other way to approach this problem?

**Comment by Nice3point** [comment]
@ThanhPhanz You can use static variables, but they must all be used within the same context, i.e. all commands must inherit from ExternalCommand and the application from ExternalApplication. If you initialize the settings in IExternalApplication it won't work, ricaun showed this here https://www.youtube.com/watch?v=cpy4J_6-8WY

**Comment by ThanhPhanz** [comment]
It works. Thank you
