### ISSUE TITLE
Add application insights to host logger 

### ISSUE THREAD

**Issue by AmeerMansour** [Nice3point/RevitToolkit#8]
I am trying to add application insights to the host and I get this error not sure what is the issue 

![image](https://github.com/user-attachments/assets/1aca16bc-e11a-4d48-9e14-d8d4b1cf07c6)
I just added Microsoft.Extensions.Logging.ApplicationInsights package and trying to use it
![image](https://github.com/user-attachments/assets/61c3b657-22dd-49d7-9331-597360f128c3)

**Comment by AmeerMansour** [comment]
I found the issue that revit uses an older version but shouldn't the assembly resolver handle that?
Microsoft.Extensions.Logging
these are the modules that loaded in the environment 
![image](https://github.com/user-attachments/assets/f3663815-d958-473f-9398-af840feeaa31)

**Comment by Nice3point** [comment]
What version of Revit are you using, 2025 or older?

**Comment by AmeerMansour** [comment]
2024

**Comment by Nice3point** [comment]
@AmeerMansour the problem and solutions are described here https://github.com/jeremytammik/RevitLookup/issues/269
you have a plugin with outdated dependencies

**Comment by AmeerMansour** [comment]
the problem is not in 3rd part the problem is revit itself uses 
	C:\Program Files\Autodesk\Revit 2024\Microsoft.Extensions.Logging.dll		version	2.02.0.18315	which doesn't have application insights extension !
	so I have to downgrade my Microsoft.Extensions.Logging to the same version .

**Comment by AmeerMansour** [comment]
if you have revit 2025 installed can you check if they are using Microsoft.Extensions.Logging version 2.02.0.18315 as well ?
as they are using it since 2020

**Comment by Nice3point** [comment]
Yes, indeed older versions of Revit include version 2.2. You can downgrade the Nuget package version for them. The 2025 version includes version 7, but it doesn't matter because the 2025 version has library isolation enabled in the Toolkit and you can use Microsoft.Extensions.Logging version 8 with no problem.

**Comment by AmeerMansour** [comment]
thanks !
it is really awful to be forced to use Microsoft.Extensions.Hosting v2 for older revit versions.
you may close this issue if you want
