### ISSUE TITLE
Revit 2023

### ISSUE THREAD

**Issue by danielgijsbers** [Nice3point/RevitToolkit#9]
The latest build gives an issue for only Revit 2023
Odd thing is the other Revit versions are fine.

![2024-08-23_10h54_32](https://github.com/user-attachments/assets/8446d373-c86d-406e-8410-7f98a8a42f5b)

**Comment by Nice3point** [comment]
RevitToolkit is not related to this issue https://github.com/jeremytammik/RevitLookup/issues/269
